[workspace]
resolver = "3"
members = ["turnip_music2", "turnip_music2_cli"]

[workspace.dependencies]
anyhow = "1.0.100"
indexmap = { version = "2.14.0", features = ["std", "serde"] }
log = "0.4.34"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
toml_edit = { version = "0.24.0+spec-1.1.0", features = ["serde"] }
